# Generated by Django 5.2.12 on 2026-04-20 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('text_ar', models.TextField()),
                ('text_en', models.TextField(blank=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('risk_level', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالٍ'), ('critical', 'حرج')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'البند',
                'verbose_name_plural': 'بنود التقييم',
                'ordering': ['section__sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=255)),
                ('license_no', models.CharField(max_length=100)),
                ('commercial_reg', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('closed', 'مغلق')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'المنشأة',
                'verbose_name_plural': 'المنشآت',
                'ordering': ['commercial_name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'قسم التقييم',
                'verbose_name_plural': 'أقسام التقييم',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'المحافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='RequiredRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'سجل مطلوب',
                'verbose_name_plural': 'السجلات المطلوبة',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('classification', models.CharField(choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جدًا'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], default='acceptable', max_length=20)),
                ('approval_status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مرفوع للمراجعة'), ('under_review', 'تحت المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='inspections.establishment')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspector_evaluations', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'التقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('assigned_to', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد التنفيذ'), ('closed', 'مغلق'), ('overdue', 'متأخر')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_logs', to='inspections.criterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_logs', to='inspections.evaluation')),
            ],
            options={
                'verbose_name': 'إجراء تصحيحي',
                'verbose_name_plural': 'الإجراءات التصحيحية',
                'ordering': ['status', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='inspections.evaluation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجلات النشاط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evaluation_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='inspections.criterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspections.evaluation')),
            ],
            options={
                'verbose_name': 'صورة التقييم',
                'verbose_name_plural': 'صور التقييم',
            },
        ),
        migrations.AddField(
            model_name='criterion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='inspections.evaluationsection'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='inspections.governorate'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'مدير النظام'), ('central', 'الإدارة المركزية'), ('manager', 'مدير محافظة'), ('inspector', 'مفتش / مقيم'), ('reviewer', 'مراجع فني')], default='inspector', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active_inspector', models.BooleanField(default=True)),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.governorate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='Wilayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wilayats', to='inspections.governorate')),
            ],
            options={
                'verbose_name': 'الولاية',
                'verbose_name_plural': 'الولايات',
                'ordering': ['governorate__name_ar', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='establishment',
            name='wilayat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='inspections.wilayat'),
        ),
        migrations.CreateModel(
            name='EvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('compliant', 'مستوفي'), ('non_compliant', 'غير مستوفي'), ('na', 'لا ينطبق'), ('observation', 'ملاحظة')], default='compliant', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('score_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_items', to='inspections.criterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.evaluation')),
            ],
            options={
                'verbose_name': 'عنصر التقييم',
                'verbose_name_plural': 'عناصر التقييم',
                'unique_together': {('evaluation', 'criterion')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='criterion',
            unique_together={('section', 'code')},
        ),
        migrations.CreateModel(
            name='EvaluationRecordCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_checks', to='inspections.evaluation')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_checks', to='inspections.requiredrecord')),
            ],
            options={
                'verbose_name': 'تحقق السجل',
                'verbose_name_plural': 'تحققات السجلات',
                'unique_together': {('evaluation', 'record')},
            },
        ),
        migrations.AddConstraint(
            model_name='establishment',
            constraint=models.UniqueConstraint(fields=('license_no', 'commercial_reg'), name='unique_establishment_license_reg'),
        ),
    ]
