# Generated by Django 5.2.12 on 2026-04-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='رقم البند')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='ترتيب البند')),
                ('text_ar', models.TextField(verbose_name='نص البند بالعربية')),
                ('text_en', models.TextField(blank=True, verbose_name='نص البند بالإنجليزية')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='الدرجة القصوى')),
                ('risk_level', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالٍ'), ('critical', 'حرج')], default='medium', max_length=10, verbose_name='مستوى الخطورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'البند',
                'verbose_name_plural': 'بنود التقييم',
                'ordering': ['section__sort_order', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_no', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='رقم المنشأة')),
                ('commercial_name', models.CharField(max_length=255, verbose_name='الاسم التجاري')),
                ('activity_type', models.CharField(max_length=255, verbose_name='النشاط الرئيسي')),
                ('license_no', models.CharField(max_length=100, verbose_name='رقم رخصة النشاط')),
                ('commercial_reg', models.CharField(max_length=100, verbose_name='رقم السجل التجاري')),
                ('manager_name', models.CharField(max_length=255, verbose_name='اسم مدير الجودة أو سلامة الغذاء')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='رقم التواصل')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الموظفين')),
                ('production_capacity', models.CharField(blank=True, max_length=255, verbose_name='الطاقة الإنتاجية')),
                ('product_types', models.TextField(blank=True, verbose_name='نوع المنتجات')),
                ('doc_commercial_register', models.FileField(blank=True, null=True, upload_to='establishment_docs/', verbose_name='السجل التجاري')),
                ('doc_municipal_license', models.FileField(blank=True, null=True, upload_to='establishment_docs/', verbose_name='الترخيص البلدي')),
                ('doc_quality_certificates', models.FileField(blank=True, null=True, upload_to='establishment_docs/', verbose_name='شهادات الجودة')),
                ('doc_factory_layout', models.FileField(blank=True, null=True, upload_to='establishment_docs/', verbose_name='مخططات المصنع')),
                ('direct_location_url', models.URLField(blank=True, verbose_name='الموقع المباشر')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('closed', 'مغلق')], default='active', max_length=20, verbose_name='حالة المنشأة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'المنشأة',
                'verbose_name_plural': 'المنشآت',
                'ordering': ['commercial_name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم القسم بالعربية')),
                ('name_en', models.CharField(max_length=255, verbose_name='اسم القسم بالإنجليزية')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='ترتيب القسم')),
            ],
            options={
                'verbose_name': 'قسم التقييم',
                'verbose_name_plural': 'أقسام التقييم',
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم المحافظة بالعربية')),
                ('name_en', models.CharField(max_length=150, verbose_name='اسم المحافظة بالإنجليزية')),
            ],
            options={
                'verbose_name': 'المحافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='RequiredRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم السجل بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='اسم السجل بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'سجل مطلوب',
                'verbose_name_plural': 'السجلات المطلوبة',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='تاريخ التقييم')),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='إجمالي النقاط المحققة')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الامتثال')),
                ('classification', models.CharField(choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], default='acceptable', max_length=20, verbose_name='التصنيف النهائي')),
                ('approval_status', models.CharField(choices=[('draft', 'مسودة'), ('completed', 'مكتمل')], default='draft', max_length=20, verbose_name='حالة التقييم')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('corrective_action', models.TextField(blank=True, verbose_name='الإجراءات التصحيحية العامة')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المتابعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء التقييم')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='inspections.establishment', verbose_name='المنشأة')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspector_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='المفتش / المقيم')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='المراجع الفني')),
            ],
            options={
                'verbose_name': 'التقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإجراء')),
                ('details', models.TextField(verbose_name='تفاصيل الإجراء')),
                ('assigned_to', models.CharField(max_length=255, verbose_name='مكلّف بالتنفيذ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد التنفيذ'), ('closed', 'مغلق'), ('overdue', 'متأخر')], default='open', max_length=20, verbose_name='حالة الإجراء')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_logs', to='inspections.criterion', verbose_name='البند')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_logs', to='inspections.evaluation', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'إجراء تصحيحي',
                'verbose_name_plural': 'الإجراءات التصحيحية',
                'ordering': ['status', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='الإجراء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنفيذ')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='inspections.evaluation', verbose_name='التقييم')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجلات النشاط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evaluation_images/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='وصف الصورة')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الالتقاط')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='inspections.criterion', verbose_name='البند')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspections.evaluation', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'صورة التقييم',
                'verbose_name_plural': 'صور التقييم',
            },
        ),
        migrations.CreateModel(
            name='EvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('compliant', 'مستوفي'), ('non_compliant', 'غير مستوفي'), ('na', 'لا ينطبق'), ('observation', 'ملاحظة')], default='compliant', max_length=20, verbose_name='النتيجة')),
                ('remarks', models.TextField(blank=True, verbose_name='الملاحظات')),
                ('corrective_action', models.TextField(blank=True, verbose_name='الإجراء التصحيحي')),
                ('score_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الدرجة المحققة')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_items', to='inspections.criterion', verbose_name='البند')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.evaluation', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'عنصر التقييم',
                'verbose_name_plural': 'عناصر التقييم',
            },
        ),
        migrations.AddField(
            model_name='criterion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='inspections.evaluationsection', verbose_name='القسم'),
        ),
        migrations.CreateModel(
            name='EvaluationTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('job_title', models.CharField(max_length=255, verbose_name='المسمى الوظيفي')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='inspections.evaluation', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'عضو فريق التقييم',
                'verbose_name_plural': 'أعضاء فريق التقييم',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='establishment',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='inspections.governorate', verbose_name='المحافظة'),
        ),
        migrations.CreateModel(
            name='EvaluationRecordCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False, verbose_name='متوفر')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_checks', to='inspections.evaluation', verbose_name='التقييم')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_checks', to='inspections.requiredrecord', verbose_name='السجل')),
            ],
            options={
                'verbose_name': 'تحقق السجل',
                'verbose_name_plural': 'تحققات السجلات',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('role', models.CharField(choices=[('admin', 'مدير النظام'), ('central', 'الإدارة المركزية'), ('manager', 'مدير محافظة'), ('inspector', 'مفتش / مقيم'), ('reviewer', 'مراجع فني')], default='inspector', max_length=30, verbose_name='الدور الوظيفي')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('is_active_inspector', models.BooleanField(default=True, verbose_name='نشط كمفتش')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.governorate', verbose_name='المحافظة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='Wilayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم الولاية بالعربية')),
                ('name_en', models.CharField(max_length=150, verbose_name='اسم الولاية بالإنجليزية')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wilayats', to='inspections.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'الولاية',
                'verbose_name_plural': 'الولايات',
                'ordering': ['governorate__name_ar', 'name_ar'],
            },
        ),
        migrations.AddField(
            model_name='establishment',
            name='wilayat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='inspections.wilayat', verbose_name='الولاية'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['visit_date'], name='evaluation_visit_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['classification'], name='evaluation_class_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['approval_status'], name='evaluation_approval_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['establishment', 'visit_date'], name='evaluation_est_visit_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['inspector', 'visit_date'], name='evaluation_inspector_visit_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveactionlog',
            index=models.Index(fields=['status'], name='corrective_status_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveactionlog',
            index=models.Index(fields=['due_date'], name='corrective_due_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationitem',
            index=models.Index(fields=['evaluation', 'status'], name='evaluation_item_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationitem',
            unique_together={('evaluation', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='criterion',
            unique_together={('section', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationrecordcheck',
            unique_together={('evaluation', 'record')},
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['commercial_name'], name='establishment_name_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['license_no'], name='establishment_license_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['commercial_reg'], name='establishment_reg_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['governorate', 'wilayat'], name='establishment_region_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['status'], name='establishment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='establishment',
            constraint=models.UniqueConstraint(fields=('license_no', 'commercial_reg'), name='unique_establishment_license_reg'),
        ),
    ]
