# Generated by Django 6.0.3 on 2026-04-28 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=150, verbose_name='المحافظة')),
                ('establishment_name', models.CharField(max_length=255, verbose_name='اسم المنشأة')),
                ('activity_type', models.CharField(max_length=255, verbose_name='نوع النشاط')),
                ('current_status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('stalled', 'متعثر')], default='not_started', max_length=20, verbose_name='الحالة الحالية')),
                ('quality_system', models.CharField(blank=True, choices=[('ISO 22000', 'ISO 22000'), ('ISO 9001', 'ISO 9001'), ('HACCP', 'HACCP'), ('GMP', 'GMP'), ('Halal', 'Halal'), ('Organic', 'Organic'), ('G.A.P', 'G.A.P'), ('Others', 'أخرى')], max_length=100, verbose_name='أنظمة الجودة وسلامة الغذاء')),
                ('custom_quality_system', models.CharField(blank=True, max_length=150, verbose_name='نظام جودة آخر')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('expected_completion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإنجاز المتوقع')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='نسبة الإنجاز (%)')),
                ('challenges', models.TextField(blank=True, verbose_name='التحديات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_followups', to='inspections.establishment', verbose_name='المنشأة المسجلة')),
            ],
            options={
                'verbose_name': 'متابعة تأهيل منشأة',
                'verbose_name_plural': 'متابعة تأهيل المنشآت',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['governorate'], name='qual_follow_gov_idx'), models.Index(fields=['current_status'], name='qual_follow_status_idx'), models.Index(fields=['expected_completion_date'], name='qual_follow_due_idx')],
            },
        ),
    ]
