# Generated by Django 5.2.12 on 2026-04-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['section__sort_order', 'sort_order', 'code'], 'verbose_name': 'البند', 'verbose_name_plural': 'بنود التقييم'},
        ),
        migrations.AddField(
            model_name='criterion',
            name='sort_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='classification',
            field=models.CharField(choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], default='acceptable', max_length=20),
        ),
    ]
