# Generated by Django 5.2.12 on 2026-04-20 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_criterion_options_criterion_sort_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveactionlog',
            name='assigned_to',
            field=models.CharField(max_length=255, verbose_name='مكلّف بالتنفيذ'),
        ),
        migrations.AlterField(
            model_name='correctiveactionlog',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق'),
        ),
        migrations.AlterField(
            model_name='correctiveactionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='correctiveactionlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='correctiveactionlog',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_logs', to='inspections.criterion', verbose_name='البند'),
        ),
        migrations.AlterField(
            model_name='correctiveactionlog',
            name='details',
            field=models.TextField(verbose_name='تفاصيل الإجراء'),
        ),
        migrations.AlterField(
            model_name='correctiveactionlog',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='correctiveactionlog',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_logs', to='inspections.evaluation', verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='correctiveactionlog',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد التنفيذ'), ('closed', 'مغلق'), ('overdue', 'متأخر')], default='open', max_length=20, verbose_name='حالة الإجراء'),
        ),
        migrations.AlterField(
            model_name='correctiveactionlog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان الإجراء'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='code',
            field=models.CharField(max_length=20, verbose_name='رقم البند'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='risk_level',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالٍ'), ('critical', 'حرج')], default='medium', max_length=10, verbose_name='مستوى الخطورة'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='inspections.evaluationsection', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='sort_order',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتيب البند'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='text_ar',
            field=models.TextField(verbose_name='نص البند بالعربية'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='text_en',
            field=models.TextField(blank=True, verbose_name='نص البند بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='weight',
            field=models.PositiveIntegerField(default=1, verbose_name='الدرجة القصوى'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='activity_type',
            field=models.CharField(max_length=255, verbose_name='النشاط الرئيسي'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='commercial_name',
            field=models.CharField(max_length=255, verbose_name='الاسم التجاري'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='commercial_reg',
            field=models.CharField(max_length=100, verbose_name='رقم السجل التجاري'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='contact_phone',
            field=models.CharField(max_length=30, verbose_name='رقم التواصل'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='inspections.governorate', verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='license_no',
            field=models.CharField(max_length=100, verbose_name='رقم رخصة النشاط'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='manager_name',
            field=models.CharField(max_length=255, verbose_name='اسم مدير الجودة أو سلامة الغذاء'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('closed', 'مغلق')], default='active', max_length=20, verbose_name='حالة المنشأة'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='wilayat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='inspections.wilayat', verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('completed', 'مكتمل'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='حالة الاعتماد'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='classification',
            field=models.CharField(choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('weak', 'ضعيف')], default='acceptable', max_length=20, verbose_name='التصنيف النهائي'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='corrective_action',
            field=models.TextField(blank=True, verbose_name='الإجراءات التصحيحية العامة'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء التقييم'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='inspections.establishment', verbose_name='المنشأة'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ المتابعة'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspector_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='المفتش / المقيم'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات عامة'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الامتثال'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='المراجع الفني'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='إجمالي النقاط المحققة'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='visit_date',
            field=models.DateField(verbose_name='تاريخ التقييم'),
        ),
        migrations.AlterField(
            model_name='evaluationactivitylog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='evaluationactivitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنفيذ'),
        ),
        migrations.AlterField(
            model_name='evaluationactivitylog',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='inspections.evaluation', verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='evaluationactivitylog',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='evaluationactivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='evaluationimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='وصف الصورة'),
        ),
        migrations.AlterField(
            model_name='evaluationimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='evaluationimage',
            name='criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='inspections.criterion', verbose_name='البند'),
        ),
        migrations.AlterField(
            model_name='evaluationimage',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspections.evaluation', verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='evaluationimage',
            name='image',
            field=models.ImageField(upload_to='evaluation_images/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='evaluationimage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='evaluationimage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AlterField(
            model_name='evaluationimage',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الالتقاط'),
        ),
        migrations.AlterField(
            model_name='evaluationitem',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_items', to='inspections.criterion', verbose_name='البند'),
        ),
        migrations.AlterField(
            model_name='evaluationitem',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.evaluation', verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='evaluationitem',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='evaluationitem',
            name='score_awarded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الدرجة المحققة'),
        ),
        migrations.AlterField(
            model_name='evaluationitem',
            name='status',
            field=models.CharField(choices=[('compliant', 'مستوفي'), ('non_compliant', 'غير مستوفي'), ('na', 'لا ينطبق'), ('observation', 'ملاحظة')], default='compliant', max_length=20, verbose_name='النتيجة'),
        ),
        migrations.AlterField(
            model_name='evaluationrecordcheck',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_checks', to='inspections.evaluation', verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='evaluationrecordcheck',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='evaluationrecordcheck',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_checks', to='inspections.requiredrecord', verbose_name='السجل'),
        ),
        migrations.AlterField(
            model_name='evaluationrecordcheck',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='evaluationsection',
            name='name_ar',
            field=models.CharField(max_length=255, verbose_name='اسم القسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='evaluationsection',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='اسم القسم بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='evaluationsection',
            name='sort_order',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتيب القسم'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='name_ar',
            field=models.CharField(max_length=150, verbose_name='اسم المحافظة بالعربية'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='name_en',
            field=models.CharField(max_length=150, verbose_name='اسم المحافظة بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='requiredrecord',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='requiredrecord',
            name='name_ar',
            field=models.CharField(max_length=255, verbose_name='اسم السجل بالعربية'),
        ),
        migrations.AlterField(
            model_name='requiredrecord',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم السجل بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.governorate', verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active_inspector',
            field=models.BooleanField(default=True, verbose_name='نشط كمفتش'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('central', 'الإدارة المركزية'), ('manager', 'مدير محافظة'), ('inspector', 'مفتش / مقيم'), ('reviewer', 'مراجع فني')], default='inspector', max_length=30, verbose_name='الدور الوظيفي'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='wilayat',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wilayats', to='inspections.governorate', verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='wilayat',
            name='name_ar',
            field=models.CharField(max_length=150, verbose_name='اسم الولاية بالعربية'),
        ),
        migrations.AlterField(
            model_name='wilayat',
            name='name_en',
            field=models.CharField(max_length=150, verbose_name='اسم الولاية بالإنجليزية'),
        ),
    ]
