# Generated by Django 5.2.12 on 2026-04-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_alter_evaluation_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='direct_location_url',
            field=models.URLField(blank=True, verbose_name='الموقع المباشر'),
        ),
    ]
