# Generated by Django 5.2.13 on 2026-06-04 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_evaluation_haccp_certificates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterFactoryClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التصنيف')),
                ('total_possible_points', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='إجمالي النقاط الممكنة')),
                ('total_earned_points', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='إجمالي النقاط المحققة')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='النسبة المئوية')),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, verbose_name='التصنيف')),
                ('decision', models.CharField(max_length=255, verbose_name='قرار المفتش')),
                ('critical_count', models.PositiveIntegerField(default=0, verbose_name='عدد المخالفات الحرجة')),
                ('items_payload', models.JSONField(blank=True, default=list, verbose_name='تفاصيل البنود')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحفظ')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_classifications', to='inspections.establishment', verbose_name='مصنع مياه الشرب')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='water_factory_classifications', to=settings.AUTH_USER_MODEL, verbose_name='المفتش / المقيم')),
            ],
            options={
                'verbose_name': 'تصنيف مصنع مياه الشرب',
                'verbose_name_plural': 'تصنيفات مصانع مياه الشرب',
                'ordering': ['-classified_at', '-created_at'],
                'indexes': [models.Index(fields=['classified_at'], name='water_classified_at_idx'), models.Index(fields=['grade'], name='water_grade_idx'), models.Index(fields=['establishment', 'classified_at'], name='water_est_classified_idx')],
            },
        ),
    ]
