# Generated by Django 5.2.12 on 2026-04-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_evaluationteammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الموظفين'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='has_commercial_register_doc',
            field=models.BooleanField(default=False, verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='has_factory_layout_doc',
            field=models.BooleanField(default=False, verbose_name='مخططات المصنع'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='has_haccp',
            field=models.BooleanField(default=False, verbose_name='HACCP'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='has_iso_22000',
            field=models.BooleanField(default=False, verbose_name='ISO 22000'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='has_municipal_license_doc',
            field=models.BooleanField(default=False, verbose_name='الترخيص البلدي'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='has_quality_certificates_doc',
            field=models.BooleanField(default=False, verbose_name='شهادات الجودة'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='other_certifications',
            field=models.TextField(blank=True, verbose_name='شهادات أخرى'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='product_types',
            field=models.TextField(blank=True, verbose_name='نوع المنتجات'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='production_capacity',
            field=models.CharField(blank=True, max_length=255, verbose_name='الطاقة الإنتاجية'),
        ),
    ]
