# Generated by Django 5.2.12 on 2026-04-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_establishment_employee_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='has_commercial_register_doc',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='has_factory_layout_doc',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='has_haccp',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='has_iso_22000',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='has_municipal_license_doc',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='has_quality_certificates_doc',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='other_certifications',
        ),
        migrations.AddField(
            model_name='establishment',
            name='doc_commercial_register',
            field=models.FileField(blank=True, null=True, upload_to='establishment_docs/', verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='doc_factory_layout',
            field=models.FileField(blank=True, null=True, upload_to='establishment_docs/', verbose_name='مخططات المصنع'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='doc_municipal_license',
            field=models.FileField(blank=True, null=True, upload_to='establishment_docs/', verbose_name='الترخيص البلدي'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='doc_quality_certificates',
            field=models.FileField(blank=True, null=True, upload_to='establishment_docs/', verbose_name='شهادات الجودة'),
        ),
    ]
